### ISSUE TITLE
getQueryParam doesn't work anymore

### ISSUE THREAD

**Issue by Firfi** [kadirahq/flow-router#269]
With latest update I found that it returns null. 

When I have some link in application (a href=) like `http://127.0.0.1:3000/home?s=SGHprbrRKtaRXKfta`

getQueryParam('s') doesn't return SGHprbrRKtaRXKfta anymore. However, route in browser is changed to http://127.0.0.1:3000/home?s=SGHprbrRKtaRXKfta. Trying to call it from the console and from triggers.

**Comment by arunoda** [comment]
I think there is an issue inside the triggers. That's by design. Anyway, inside the triggers you can have the direct access to the context.

See:

~~~js
FlowRouter.route('/:postId', {
  triggersEnter: [function(context) {
    console.log(context.queryParams);
  }],
  action(params) {
    ...
  }
});
~~

But this is working pretty well in the browser console.

**Comment by Firfi** [comment]
Thanks @arunoda for the advice. I tried to work with context and it did the job. However, I really called getQueryParam() from the triggerEnter before. It didn't worked and didn't got this param, and moreover prevented another getQueryParam() console calls from working as expected.

With context it works fine though, I just get 's' from there.

**Comment by arunoda** [comment]
It's not possible to access `getQueryParam` inside the context. That's because you are not yet inside that route yet.
