### ISSUE TITLE
SSR Context Breaking CollectionFS methods

### ISSUE THREAD

**Issue by zachariahtimothy** [kadirahq/flow-router#352]
I have found on the server side rendering of React components the SSR context / Meteor.prototype.find()/findOne() methods break ColectionsFS .url() method for getting media URL's. (See issue: https://github.com/CollectionFS/Meteor-CollectionFS/issues/835). This makes me nervous of what other functionality overriding Mongo Collections might break. Is there a way to use hooks instead of overriding the Meteor mongo methods and breaking things like CollectionFS? 

Not sure if it is helpful, but I did confirm the query always runs through flow routers find prototype and it only breaks when ssr context is defined.  Here is the offending code:
```
Mongo.Collection.prototype.find = function(selector, options) {                     // 20
  selector = selector || {};                                                        // 21
  var collName = this._name;                                                        // 22
  var ssrContext = FlowRouter.ssrContext.get();                                     // 23
  if(ssrContext && !FlowRouter.inSubscription.get()) {                              // 24
    var collection = ssrContext.getCollection(collName);                            // 25
    var cursor = collection.find(selector, options);                                // 26
    return cursor;                                                                  // 27
  }                                                                                 // 28
                                                                                    // 29
  return originalFind.call(this, selector, options);                                // 30
};
```

**Comment by arunoda** [comment]
Okay. Seems like CFS overriding the Meteor's Mongo collection's find and that's why this is. And you are correct. 

We need this functionality because, we must get data from the ssrContext. It deals with subscriptions to get correct data. Technically, we can't check whether this is CFS or not here. But I'm looking whether to figure out this is a original Meteor collection or not.

May be someone from CFS could help me to figure it out. Otherwise, you can do this as a remedy.

```js
if(Meteor.isServer) {
  var media = FlowRouter.ssrContext.withValue(null, function() {
    return Collections.Media.findOne();
  });
} else {
  var media = Collections.Media.findOne();
}
```

**Comment by zachariahtimothy** [comment]
@arunoda thank you for the reply. Your solution will work but it would be brutal to add that chunk of code to nearly every component that uses media (most of them). I switched to react-router-ssr and it works well on on the DDP front utilizing FastRender but then again ReactRouter is an absolute nightmare to deal with. I will play around more with FlowRouter to see what else I can do to make that work, FlowRouter is SOOO easy to use!

**Comment by arunoda** [comment]
It works with react-router-ssr is because, they don't filter data by subscriptions in the server. So, it's possible to send your whole dataset to the client. 
We are maintaining a SSR context with subscription data and that's why CFS code break.

But again, I can't find a way to differentiate CFS collection and a normal collection. If we can find it then, the fix is simple.

**Comment by zachariahtimothy** [comment]
Thanks for your guidance @arunoda. I had forked and modified react-router-ssr to support server subscription queries which worked but decided to try your solution so I can use Flow Rotuer.  I did the following based on your suggestion at the collection level and it seems to work great.

````
if (Meteor.isServer) {
    let originalFind = App.Collections.Media.find;
    let originalFindOne = App.Collections.Media.findOne;

    App.Collections.Media.__proto__.findOne = function (selector, options) {
        let self = this;
        return FlowRouter.ssrContext.withValue(null, function() {
            return originalFindOne.call(self, selector, options);
        });
    };

    App.Collections.Media.__proto__.find = function (selector, options) {
        let self = this;
        return FlowRouter.ssrContext.withValue(null, function() {
            return originalFind.call(self, selector, options);
        }); 
    };
}
````

**Comment by arunoda** [comment]
I'm closing this for now. I can't think of a better way than this.

**Comment by neopostmodern** [comment]
@zachariahtimothy - thanks for the code snippet! Have you been able to figure out how to generate CFS tokens on the server? I am currently running into the following issue:
```txt
 (client) McbWD8pJMHPE/le.JPG?token=eyJhdXRoVG9rZW
 (server) McbWD8pJMHPE/le.JPG?store=large" title="
```
...which basically says that SSR CFS doesn't generate a token, probably because it assumes that there is no need to on the server. (And without a token all you get is `403` instead of images)

*I can't put into an `NoSSR` block because I am injecting the CFS images into `marked` and `dangerouslySetInnerHTML`.*
