### ISSUE TITLE
Getting rid of FlowRouter.watchPathChange()?

### ISSUE THREAD

**Issue by SachaG** [kadirahq/flow-router#358]
I really like FlowRouter, but I feel like `FlowRouter.watchPathChange()` to add reactivity to `FlowRouter.current()` isn't very elegant, and is also easy to forget, especially when you're starting out. 

Wouldn't it be possible instead to pass an option to `current()`? So `FlowRouter.current(true)` would be reactive, but `FlowRouter.current()` wouldn't?

**Comment by arunoda** [comment]
So, here's the thing. We need `watchPathChange` as a way to watch without the need of the current() object. And the same time, I get it what you are saying.

But, I want all the APIs to be verbose and unambiguous. We had a such an API called, reativeCurrent() but removed it before.
Also, I want everyone to avoid using `.current()` instead of the `.getParams()` API or directly passing them via from the router's action. 

For React, it's easy as simply passing it. For Blaze, we need to use Blaze+ to do it without compromising the performance.

**Comment by SachaG** [comment]
OK, that makes sense. Actually the only reason I need `current()` is to get the current path. If there was a `FlowRouter.getPath()` then I could probably remove it from my codebase entirely :)
