### ISSUE TITLE
Security and SSR

### ISSUE THREAD

**Issue by arunoda** [kadirahq/flow-router#422]
SSR caching make preserve FastRender loginToken in the HTML. So, there is a possibility to leak one user's loginToken to others. We need to prevent that.

There may also some security issues related to SSR. Get some help from experts.

**Comment by withinboredom** [comment]
I don't see how this is an issue. If you are using SSL (which you should if you have any logins at all, if only to protect people from themselves -- like reusing passwords across sites) ... if you are using SSL, then the headers and html are encrypted. You should turn off caching also, to prevent anyone from accidentally getting a page from a user that is not themselves.

If you are not using SSL ~~then people are dumb for trusting you for any information~~ then hackers could easily capture a loginToken from either the headers or html. It doesn't matter that "it leaks" since anyone along the connection path can read any of it.

**Comment by arunoda** [comment]
Now in the caching config, we are looking to bring to userId to build the cacheKey. 
See: https://github.com/kadirahq/flow-router/issues/421

This could prevent the caching related security issue mentioned above.

**Comment by arunoda** [comment]
Now this won't be an issue.
We implemented caching with taking the userId into the mix.
