### ISSUE TITLE
Why must redirect be called within the same event loop cycle?

### ISSUE THREAD

**Issue by trusktr** [kadirahq/flow-router#451]
What will happen otherwise?

What do I do about a triggersEnter function that has this:

```js
// check the user is logged in (we need to use the data too):
let user = Meteor.user() // sometimes the data is not ready until later...
```

**Comment by trusktr** [comment]
It'd be cool if we could use async/await:

```js
triggersEnter: [async function(ctx, redirect) {
  let user = await currentUser() // returns a promise
  if (!user) redirect('/login')
}],
```

**Comment by arunoda** [comment]
If we allow it, we need to handle loading stuff in the router level. So, everything in the router must happen in the same eventloop.

**Comment by trusktr** [comment]
> handle loading stuff in the router level

@arunoda Do you mean we'll have to wait for async results in the trigger? Is that a bad thing and if so, why?

**Comment by arunoda** [comment]
It's not `async` syntax is bad or otherwise it's kind a hard to write code. We think route is a user action. It should not block the app in anyway.

So, when you make the `async await` there is a time in between the route change. So, in that time we need to show some loading screen or do something. FlowRouter don't do that.
That's why we avoid doing this.

**Comment by trusktr** [comment]
You're right. It makes sense to keep all triggers synchronous. I'll just use an async iife in the action:

```js
action: function() {
  !async function() {
    // ..
  }()
}
```

**Comment by trusktr** [comment]
@arunoda Turns out, Express is doing a similar thing with async/await: https://strongloop.com/strongblog/async-error-handling-expressjs-es7-promises-generators/
