### ISSUE TITLE
Throw warning if href is used in a link (instead of FlowRouter.go())

### ISSUE THREAD

**Issue by muhang** [kadirahq/flow-router#480]
Just an idea; after debugging an issue in a shared codebase today, I discovered many problems were caused by using an href attribute on an <a> (instead of FlowRouter.go()), but no console warnings or errors were emitted. It may be useful for a warning to get thrown in this case.

**Comment by arunoda** [comment]
I think you should use hrefs. Otherwise, google can't index your pages.

**Comment by TedAvery** [comment]
I think I've experienced the same issue as @muhang and he has just worded it in the reverse. If I have `<a onClick={this.handleClick}>link</a>`, and my `handleClick` method calls `FlowRouter.go()`, there is an error that `path` is required to use `FlowRouter.go()`. I later realized that FlowRouter is trying to find a path in an `href` property to follow, even though I was trying to do my navigating in the `onClick` handler.

The fix was to change to `<button>` instead, or to use a direct `href` property. This didn't throw any errors before, which I think was better.

**Comment by arunoda** [comment]
I think we can close this.
